### ISSUE TITLE
Rework of an existing item

### ISSUE THREAD

**Issue by Sabertoria1** [Ben987/Bondage-Club-Server#159]
Since I'm the person who requested the item called "smooth latex mask" I want to request that the item requested by me gets reworked in a way that fulfills the request of said item.

Therefore this is the list of changes that needs to be applied in order to make the item the way it was requested by me:

- removing the options to change the eyes to only allow a smooth look
- removing the coverage option to only have a mask the hides the face but NOT the hair and the hair accessories
- removing all mouth options besides smooth and onahole
- changing the one way see through option to allow seeing more of the room (atm u only see the people adjacent to, yourself)

I hope this issue gets fixed quickly and properly.

**Comment by elliesec** [comment]
A few points to note here:

1. This repository isn't really the place to make requests on the game. You'd be better off raising something in the [front end repository](https://gitgud.io/BondageProjects/Bondage-College), where there's more active development, or in the game's [Discord server](https://discordapp.com/invite/dkWsEjf).
2. For your first three points: you're suggesting removing features from the item. I don't see any reason to do that - it almost certainly won't be a popular decision with players, and you can still use it in the way you've described above
3. On your fourth point - the mask just applies a standard blinding effect. The fact that you can only see players adjacent to yourself is caused by your settings ("Preferences" > "Immersion" > "Hide non-adjacent players while partially blind")
4. Regardless of who requested it, it's very much up to the person that created it and put it into the game whether they want to act on this request (@SepiaOulomenohn IIRC)

**Comment by Sabertoria1** [comment]
If im being honest, the way the item got created and added is not the way I
requested the item.

Therefore I would see this as an issue because it was kinda defined by my
request what I was aiming for with the requested item but the end product
is not the way it should have been. I kinda feel betrayed by this not
fulfilled requested. It's kinda like ordering for example apples and
getting tomatoes instead.

Ellie ***@***.***> schrieb am Sa., 19. Nov. 2022, 18:50:

**Comment by elliesec** [comment]
Like I said, changes like this are up to the creator of the item. _Requests_ are done for free by creators - they have creative freedom in how they want to make the item.

On the other hand, if you _commissioned_ (i.e. paid for) the creation of the item, and there was a formal agreement as to what the final product would be which wasn't fulfilled, then you are absolutely entitled to take that up with the creator (and I'd assume you have their contact details if you paid for it).

**Comment by Sabertoria1** [comment]
When I remember correctly I was not allowed to request an item and pay for
it. Which is kinda sad imo. It's really sad that this item got ruined this
way....

I really wish this would get changed to have it the way it was supposed to
be. If I could I would pay for these changes to get applied.

Ellie ***@***.***> schrieb am Sa., 19. Nov. 2022, 20:32:

**Comment by Sabertoria1** [comment]
It's a shame that I'm literally forced to block and hide the item I requested.

**Comment by Ben987** [comment]
Sorry, this is not the place to make such request.  Please contact us on Discord, Patreon or DeviantArt.

**Comment by Sabertoria1** [comment]
This is the only way to contact the contributors, since a staff member banned me out of personal reasons from your Discord.

She was not okay with my opinion and banned me for this.

**Comment by Sabertoria1** [comment]
It's such a shame that the idea of my item I requested gets slaughtered in such a rude way!!
